### ISSUE TITLE
kwallet5/gnome-keyring and systemd_homed have an incorrect combined common-auth setup 

### ISSUE THREAD

**Issue by Kalanyr** [SUSE/pam-config#13]
In common-auth systemd_homed is defined as sufficient , and gnome-keyring and kwallet5 are marked as optional, however they are written into common-auth after systemd_homed which means that they are never run and hence the wallet isn't unlocked.   

I did some very basic testing and it appears sufficient to move these two before systemd_homed in common-auth at which point they function correctly.

**Comment by thkukuk** [comment]
Correct, systemd_home needs to be after this two modules, and it is even documented this way in the pam-config code. Seems who ever added pam_systemd_home didn't bother. Fixed.
