### ISSUE TITLE
mod_pam_lastlog2.c is missing in git

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/pam-config#18]
https://github.com/SUSE/pam-config/commit/dce578c5b1b2787a5b84e3ed7bee9372a9a4cfa5#diff-4cb884d03ebb901069e4ee5de5d02538c40dd9b39919c615d8eaa9d364bbbd77R38

added a file to the Makefile.am that is not in git. hence the build is broken.

**Comment by thkukuk** [comment]
Fixed
