### ISSUE TITLE
Using pam-u2f with pam-config doesn't seem to work

### ISSUE THREAD

**Issue by mufeedali** [SUSE/pam-config#24]
Hi,

I tried to use pam-config to generate the correct common-auth file. I ran:
```bash
sudo pam-config --service common-auth -a --u2f --u2f-cue --u2f-authfile=/etc/Yubico/u2f_keys --debug
```

From my understanding from the manpage, which was the only resource i could find, this should have worked. But no changes were made to the `/etc/pam.d/common-auth` or `/etc/pam.d/common-auth-pc`.

I see this `**** write config for pam_u2f.so (auth, enabled)` in the log but theres still no changes to the file.

Could you let me know what I'm doing wrong or confirm this is a bug?

**Comment by thkukuk** [comment]
`common-auth` is not a name of an existing service. Please use a valid service like `login`, `sshd`, `gdm` or something similar.

**Comment by mufeedali** [comment]
I can't find sddm, login, etc in `/etc/pam.d/` but I can find them in `/usr/lib/pam.d/`. I could however, find `common-auth`, which is what I tried to work with. What should I be doing here? I assume I should be generating a new configuration in `/etc/pam.d` using `pam-config`? Will that safely override the contents of `/usr/lib/pam.d/`?

**Comment by thkukuk** [comment]
Mufeed Ali ***@***.***> schrieb am Do., 28. Dez. 2023, 13:00:

> I can't find sddm, login, etc in /etc/pam.d/
>

Correct.

> but I can find them in /usr/lib/pam.d/.
>

Correct. Please make yourself at first familiar with how PAM configuration
files are working.

> I could however, find common-auth, which is what I tried to work with.
> What should I be doing here? I assume I should be generating a new
> configuration in /etc/pam.d using pam-config? Will that safely override
> the contents of /usr/lib/pam.d/?
>

Just follow the documentation.
